// BACKEND INTEGRATION: All data below should come from your API/WebSocket server
// Replace MOCK_CONVERSATIONS with GET /api/conversations
// Replace MOCK_MESSAGES with GET /api/conversations/:id/messages
// Replace MOCK_USERS with GET /api/users/search?q=query
// Replace ONLINE_STATUSES with WebSocket 'status_update' events

import { Conversation, Message, MockUser, OnlineStatus } from './types';

const now = new Date();
const mins = (n: number) => new Date(now.getTime() - n * 60 * 1000).toISOString();
const hours = (n: number) => new Date(now.getTime() - n * 60 * 60 * 1000).toISOString();
const days = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_USERS: MockUser[] = [
  { username: 'sarahkim', displayName: 'Sarah Kim', avatarColor: 'purple', bio: 'Product designer @ Vercel' },
  { username: 'marcuslee', displayName: 'Marcus Lee', avatarColor: 'green', bio: 'Full-stack engineer' },
  { username: 'priyapatel', displayName: 'Priya Patel', avatarColor: 'orange', bio: 'Data scientist' },
  { username: 'jordanwu', displayName: 'Jordan Wu', avatarColor: 'teal', bio: 'DevOps engineer' },
  { username: 'linamoreau', displayName: 'Lina Moreau', avatarColor: 'pink', bio: 'UX researcher' },
  { username: 'tomaszk', displayName: 'Tomasz Kowalski', avatarColor: 'indigo', bio: 'Backend architect' },
  { username: 'ameliahart', displayName: 'Amelia Hart', avatarColor: 'red', bio: 'Mobile developer' },
  { username: 'devonross', displayName: 'Devon Ross', avatarColor: 'blue', bio: 'Security engineer' },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-001',
    otherUserId: 'sarahkim',
    otherUserName: 'Sarah Kim',
    otherUserUsername: 'sarahkim',
    avatarColor: 'purple',
    lastMessage: 'Can you review the PR I pushed this morning?',
    lastMessageTime: mins(8),
    unreadCount: 3,
  },
  {
    id: 'conv-002',
    otherUserId: 'marcuslee',
    otherUserName: 'Marcus Lee',
    otherUserUsername: 'marcuslee',
    avatarColor: 'green',
    lastMessage: 'The deployment went through 🚀',
    lastMessageTime: mins(45),
    unreadCount: 0,
  },
  {
    id: 'conv-003',
    otherUserId: 'priyapatel',
    otherUserName: 'Priya Patel',
    otherUserUsername: 'priyapatel',
    avatarColor: 'orange',
    lastMessage: 'The model accuracy is at 94.2% now',
    lastMessageTime: hours(2),
    unreadCount: 1,
  },
  {
    id: 'conv-004',
    otherUserId: 'jordanwu',
    otherUserName: 'Jordan Wu',
    otherUserUsername: 'jordanwu',
    avatarColor: 'teal',
    lastMessage: 'Kubernetes cluster is back up',
    lastMessageTime: hours(5),
    unreadCount: 0,
  },
  {
    id: 'conv-005',
    otherUserId: 'linamoreau',
    otherUserName: 'Lina Moreau',
    otherUserUsername: 'linamoreau',
    avatarColor: 'pink',
    lastMessage: 'User testing session is at 3pm tomorrow',
    lastMessageTime: days(1),
    unreadCount: 0,
  },
  {
    id: 'conv-006',
    otherUserId: 'tomaszk',
    otherUserName: 'Tomasz Kowalski',
    otherUserUsername: 'tomaszk',
    avatarColor: 'indigo',
    lastMessage: 'I pushed the database migration scripts',
    lastMessageTime: days(2),
    unreadCount: 7,
  },
  {
    id: 'conv-007',
    otherUserId: 'ameliahart',
    otherUserName: 'Amelia Hart',
    otherUserUsername: 'ameliahart',
    avatarColor: 'red',
    lastMessage: 'iOS build passed all tests ✅',
    lastMessageTime: days(3),
    unreadCount: 0,
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  'conv-001': [
    {
      id: 'msg-001-001',
      conversationId: 'conv-001',
      senderId: 'alexchen',
      senderName: 'Alex Chen',
      text: 'Hey Sarah! How is the new design system coming along?',
      timestamp: days(2),
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-001-002',
      conversationId: 'conv-001',
      senderId: 'sarahkim',
      senderName: 'Sarah Kim',
      text: 'Going great! Just finished the color token system. It took a while to get the dark mode contrast ratios right.',
      timestamp: new Date(new Date(days(2)).getTime() + 5 * 60000).toISOString(),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-001-003',
      conversationId: 'conv-001',
      senderId: 'sarahkim',
      senderName: 'Sarah Kim',
      text: 'Also added the typography scale — I think you will love the heading weights.',
      timestamp: new Date(new Date(days(2)).getTime() + 6 * 60000).toISOString(),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-001-004',
      conversationId: 'conv-001',
      senderId: 'alexchen',
      senderName: 'Alex Chen',
      text: 'That is awesome! Can you share the Figma link?',
      timestamp: new Date(new Date(days(2)).getTime() + 15 * 60000).toISOString(),
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-001-005',
      conversationId: 'conv-001',
      senderId: 'sarahkim',
      senderName: 'Sarah Kim',
      text: 'https://figma.com/file/design-system-v2 — let me know what you think!',
      timestamp: new Date(new Date(days(2)).getTime() + 18 * 60000).toISOString(),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-001-006',
      conversationId: 'conv-001',
      senderId: 'alexchen',
      senderName: 'Alex Chen',
      text: 'Looks incredible. The component library is really clean.',
      timestamp: days(1),
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-001-007',
      conversationId: 'conv-001',
      senderId: 'sarahkim',
      senderName: 'Sarah Kim',
      text: 'Thanks! I spent a lot of time on the button states. There are now 6 variants.',
      timestamp: new Date(new Date(days(1)).getTime() + 10 * 60000).toISOString(),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-001-008',
      conversationId: 'conv-001',
      senderId: 'sarahkim',
      senderName: 'Sarah Kim',
      text: 'Can you review the PR I pushed this morning?',
      timestamp: mins(8),
      status: 'delivered',
      isOwn: false,
    },
  ],
  'conv-002': [
    {
      id: 'msg-002-001',
      conversationId: 'conv-002',
      senderId: 'marcuslee',
      senderName: 'Marcus Lee',
      text: 'Hey, are you around? Need to talk about the API rate limiting issue.',
      timestamp: hours(3),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-002-002',
      conversationId: 'conv-002',
      senderId: 'alexchen',
      senderName: 'Alex Chen',
      text: 'Yes, what is going on?',
      timestamp: new Date(new Date(hours(3)).getTime() + 3 * 60000).toISOString(),
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-002-003',
      conversationId: 'conv-002',
      senderId: 'marcuslee',
      senderName: 'Marcus Lee',
      text: 'We were hitting 429s on the /messages endpoint during load testing. I bumped the limit to 500 req/min per user.',
      timestamp: new Date(new Date(hours(3)).getTime() + 5 * 60000).toISOString(),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-002-004',
      conversationId: 'conv-002',
      senderId: 'alexchen',
      senderName: 'Alex Chen',
      text: 'Good catch. Did you add exponential backoff on the client side too?',
      timestamp: new Date(new Date(hours(3)).getTime() + 8 * 60000).toISOString(),
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-002-005',
      conversationId: 'conv-002',
      senderId: 'marcuslee',
      senderName: 'Marcus Lee',
      text: 'Yes — starts at 1s, doubles up to 30s max. Tested it and it handles reconnects cleanly.',
      timestamp: new Date(new Date(hours(3)).getTime() + 11 * 60000).toISOString(),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-002-006',
      conversationId: 'conv-002',
      senderId: 'alexchen',
      senderName: 'Alex Chen',
      text: 'Perfect. Deploy it to staging first and we will monitor for 24h.',
      timestamp: hours(2),
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-002-007',
      conversationId: 'conv-002',
      senderId: 'marcuslee',
      senderName: 'Marcus Lee',
      text: 'The deployment went through 🚀',
      timestamp: mins(45),
      status: 'read',
      isOwn: false,
    },
  ],
  'conv-003': [
    {
      id: 'msg-003-001',
      conversationId: 'conv-003',
      senderId: 'alexchen',
      senderName: 'Alex Chen',
      text: 'Priya, how is the recommendation model looking?',
      timestamp: hours(4),
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-003-002',
      conversationId: 'conv-003',
      senderId: 'priyapatel',
      senderName: 'Priya Patel',
      text: 'Better than expected! We retrained on the last 90 days of data and the recall jumped significantly.',
      timestamp: new Date(new Date(hours(4)).getTime() + 12 * 60000).toISOString(),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-003-003',
      conversationId: 'conv-003',
      senderId: 'priyapatel',
      senderName: 'Priya Patel',
      text: 'The model accuracy is at 94.2% now',
      timestamp: hours(2),
      status: 'delivered',
      isOwn: false,
    },
  ],
  'conv-004': [
    {
      id: 'msg-004-001',
      conversationId: 'conv-004',
      senderId: 'jordanwu',
      senderName: 'Jordan Wu',
      text: 'FYI — the prod cluster had a brief outage. Investigating now.',
      timestamp: hours(6),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-004-002',
      conversationId: 'conv-004',
      senderId: 'alexchen',
      senderName: 'Alex Chen',
      text: 'On it. What is the scope?',
      timestamp: new Date(new Date(hours(6)).getTime() + 2 * 60000).toISOString(),
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-004-003',
      conversationId: 'conv-004',
      senderId: 'jordanwu',
      senderName: 'Jordan Wu',
      text: 'WebSocket service pods were OOMKilled. Bumping memory limits and restarting.',
      timestamp: new Date(new Date(hours(6)).getTime() + 4 * 60000).toISOString(),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-004-004',
      conversationId: 'conv-004',
      senderId: 'jordanwu',
      senderName: 'Jordan Wu',
      text: 'Kubernetes cluster is back up',
      timestamp: hours(5),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-004-005',
      conversationId: 'conv-004',
      senderId: 'alexchen',
      senderName: 'Alex Chen',
      text: 'Great work, thanks for the quick response.',
      timestamp: new Date(new Date(hours(5)).getTime() + 5 * 60000).toISOString(),
      status: 'read',
      isOwn: true,
    },
  ],
  'conv-005': [
    {
      id: 'msg-005-001',
      conversationId: 'conv-005',
      senderId: 'linamoreau',
      senderName: 'Lina Moreau',
      text: 'The usability study results are in. 8 out of 10 users found the onboarding flow confusing.',
      timestamp: days(1),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-005-002',
      conversationId: 'conv-005',
      senderId: 'alexchen',
      senderName: 'Alex Chen',
      text: 'That is higher than expected. What part specifically?',
      timestamp: new Date(new Date(days(1)).getTime() + 8 * 60000).toISOString(),
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-005-003',
      conversationId: 'conv-005',
      senderId: 'linamoreau',
      senderName: 'Lina Moreau',
      text: 'The permission request screen. Users do not understand why we need contacts access.',
      timestamp: new Date(new Date(days(1)).getTime() + 15 * 60000).toISOString(),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-005-004',
      conversationId: 'conv-005',
      senderId: 'linamoreau',
      senderName: 'Lina Moreau',
      text: 'User testing session is at 3pm tomorrow',
      timestamp: new Date(new Date(days(1)).getTime() + 20 * 60000).toISOString(),
      status: 'read',
      isOwn: false,
    },
  ],
  'conv-006': [
    {
      id: 'msg-006-001',
      conversationId: 'conv-006',
      senderId: 'tomaszk',
      senderName: 'Tomasz Kowalski',
      text: 'The schema migration for the messages table is ready. Added read_at timestamp and index on conversation_id + created_at.',
      timestamp: days(2),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-006-002',
      conversationId: 'conv-006',
      senderId: 'alexchen',
      senderName: 'Alex Chen',
      text: 'Did you handle the backfill for existing rows?',
      timestamp: new Date(new Date(days(2)).getTime() + 20 * 60000).toISOString(),
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-006-003',
      conversationId: 'conv-006',
      senderId: 'tomaszk',
      senderName: 'Tomasz Kowalski',
      text: 'Yes, batched in groups of 10k rows to avoid table locks. Should take about 40 minutes on prod.',
      timestamp: new Date(new Date(days(2)).getTime() + 25 * 60000).toISOString(),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-006-004',
      conversationId: 'conv-006',
      senderId: 'tomaszk',
      senderName: 'Tomasz Kowalski',
      text: 'I pushed the database migration scripts',
      timestamp: days(2),
      status: 'delivered',
      isOwn: false,
    },
  ],
  'conv-007': [
    {
      id: 'msg-007-001',
      conversationId: 'conv-007',
      senderId: 'ameliahart',
      senderName: 'Amelia Hart',
      text: 'Fixed the push notification crash on iOS 17.3. The entitlement was missing from the provisioning profile.',
      timestamp: days(3),
      status: 'read',
      isOwn: false,
    },
    {
      id: 'msg-007-002',
      conversationId: 'conv-007',
      senderId: 'alexchen',
      senderName: 'Alex Chen',
      text: 'Classic Apple. Good catch though.',
      timestamp: new Date(new Date(days(3)).getTime() + 5 * 60000).toISOString(),
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-007-003',
      conversationId: 'conv-007',
      senderId: 'ameliahart',
      senderName: 'Amelia Hart',
      text: 'iOS build passed all tests ✅',
      timestamp: new Date(new Date(days(3)).getTime() + 30 * 60000).toISOString(),
      status: 'read',
      isOwn: false,
    },
  ],
};

export const ONLINE_STATUSES: Record<string, OnlineStatus> = {
  sarahkim: { isOnline: true },
  marcuslee: { isOnline: true },
  priyapatel: { isOnline: false, lastSeen: new Date(Date.now() - 25 * 60000).toISOString() },
  jordanwu: { isOnline: false, lastSeen: new Date(Date.now() - 2 * 60 * 60000).toISOString() },
  linamoreau: { isOnline: true },
  tomaszk: { isOnline: false, lastSeen: new Date(Date.now() - 5 * 60 * 60000).toISOString() },
  ameliahart: { isOnline: false, lastSeen: new Date(Date.now() - 24 * 60 * 60000).toISOString() },
  devonross: { isOnline: true },
};